"""Update User model with blockchain_address

Revision ID: 3e751ec54f7e
Revises: 49433714226c
Create Date: 2024-12-16 11:12:15.412134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e751ec54f7e'
down_revision = '49433714226c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockchain_address', sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blockchain_address')

    # ### end Alembic commands ###
