"""Initial migration

Revision ID: 73f458755c6a
Revises: add_blockchain_fields
Create Date: 2025-01-13 09:04:29.234409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f458755c6a'
down_revision = 'add_blockchain_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transformations', schema=None) as batch_op:
        batch_op.drop_index('idx_transformations_date')
        batch_op.drop_index('idx_transformations_user')

    op.drop_table('transformations')
    with op.batch_alter_table('noble_ranks', schema=None) as batch_op:
        batch_op.drop_index('idx_noble_ranks_level')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_status')
        batch_op.drop_index('idx_transactions_user')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer_id', sa.Integer(), nullable=True))
        batch_op.drop_index('idx_users_email')
        batch_op.create_foreign_key(None, 'users', ['referrer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.drop_column('referrer_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_user', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_transactions_status', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('noble_ranks', schema=None) as batch_op:
        batch_op.create_index('idx_noble_ranks_level', ['level'], unique=False)

    op.create_table('transformations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transformations', schema=None) as batch_op:
        batch_op.create_index('idx_transformations_user', ['user_id', 'status'], unique=False)
        batch_op.create_index('idx_transformations_date', ['created_at', 'status'], unique=False)

    # ### end Alembic commands ###
