"""Update user model and add relationships

Revision ID: 95540031f70c
Revises: 05cb0a0a7ce1
Create Date: 2024-12-30 14:38:45.002533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95540031f70c'
down_revision = '05cb0a0a7ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_accounts')
    op.drop_table('users')
    op.drop_table('noble_ranks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noble_ranks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rank_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('money_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
